---
- name: Copy Nginx repo
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo

- name: Install Nginx
  yum: name=nginx state=latest

- name: Copy Nginx default config
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: Set Nginx to auto start
  service: name=nginx state=started enabled=yes
  notify: restart nginx
